name: CI

on:
  push:
    tags:
      - '*'

jobs:

  build-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install npm modules
        run: npm ci
      - name: Build
        run: npm start
      - name: Zip archives
        run: |
          for dir in *
          do
            pushd $dir
              zip -r ../$dir.zip .
            popd
          done
        working-directory: dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extensions
          path: dist/*.zip

  build-safari-app:
    needs: [build-extensions]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download extensions artifact
        uses: actions/download-artifact@v2
        with:
          name: extensions
          path: dist
      - name: Unzip the extension
        run: unzip safari.zip -d safari
        working-directory: dist
      - name: Import certificate
        uses: keeweb/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      - name: Build
        run: xcodebuild -scheme "KeeWeb Connect" -configuration Release -derivedDataPath dist -archivePath dist/archive archive
        working-directory: xcode
      - name: Package
        run: productbuild "--sign" "$APPLE_INSTALLER_IDENTITY" --component "dist/archive.xcarchive/Products/Applications/KeeWeb Connect.app" "/Applications" "dist/KeeWeb Connect.pkg"
        working-directory: xcode
        env:
          APPLE_INSTALLER_IDENTITY: ${{ secrets.APPLE_INSTALLER_IDENTITY }}
#      - name: Notarize
#        uses: devbotsxyz/xcode-notarize@v1
#        with:
#          product-path: xcode/dist/archive.xcarchive/Products/Applications/KeeWeb Connect.app
#          appstore-connect-username: ${{ secrets.APPLE_NOTARIZATION_USERNAME }}
#          appstore-connect-password: ${{ secrets.APPLE_NOTARIZATION_PASSWORD }}
#      - name: Staple
#        uses: devbotsxyz/xcode-staple@v1
#        with:
#          product-path: xcode/dist/archive.xcarchive/Products/Applications/KeeWeb Connect.app
      - name: Compress
        run: zip -r ../../../KeeWeb\ Connect.app.zip KeeWeb\ Connect.app
        working-directory: xcode/dist/archive.xcarchive/Products/Applications
      - name: Upload app artifact
        uses: actions/upload-artifact@v2
        with:
          name: KeeWeb Connect.app
          path: xcode/dist/KeeWeb Connect.app.zip
      - name: Upload pkg artifact
        uses: actions/upload-artifact@v2
        with:
          name: KeeWeb Connect.pkg
          path: xcode/dist/KeeWeb Connect.pkg

  build-host-linux-x64:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -B build .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-linux-x64
          path: native-messaging-host/build/keeweb-native-messaging-host

  build-host-darwin-x64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -B build .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-darwin-x64
          path: native-messaging-host/build/keeweb-native-messaging-host

  build-host-darwin-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -B build .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-darwin-arm64
          path: native-messaging-host/build/keeweb-native-messaging-host

  build-host-win32-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -B build -A x64 .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-win32-x64
          path: native-messaging-host/build/MinSizeRel/keeweb-native-messaging-host.exe

  build-host-win32-ia32:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -B build -A win32 .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-win32-ia32
          path: native-messaging-host/build/MinSizeRel/keeweb-native-messaging-host.exe

  build-host-win32-arm64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CMake configure
        run: cmake -B build -A arm64 .
        working-directory: native-messaging-host
      - name: CMake build
        run: cmake --build build --config MinSizeRel
        working-directory: native-messaging-host
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-messaging-host-win32-arm64
          path: native-messaging-host/build/MinSizeRel/keeweb-native-messaging-host.exe

  publish:
    needs:
      - build-extensions
      - build-safari-app
      - build-host-linux-x64
      - build-host-darwin-x64
      - build-host-darwin-arm64
      - build-host-win32-x64
      - build-host-win32-ia32
      - build-host-win32-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download extensions artifact
        uses: actions/download-artifact@v2
        with:
          name: extensions
          path: extensions
      - name: Download Safari app artifact
        uses: actions/download-artifact@v2
        with:
          name: KeeWeb Connect.app
          path: xcode/dist
      - name: Download Safari pkg artifact
        uses: actions/download-artifact@v2
        with:
          name: KeeWeb Connect.pkg
          path: xcode/dist
      - name: Download linux-x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-linux-x64
          path: packages/native-messaging-host/linux-x64
      - name: Download darwin-x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-darwin-x64
          path: packages/native-messaging-host/darwin-x64
      - name: Download darwin-arm64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-darwin-arm64
          path: packages/native-messaging-host/darwin-arm64
      - name: Download win32-x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-win32-x64
          path: packages/native-messaging-host/win32-x64
      - name: Download win32-ia32 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-win32-ia32
          path: packages/native-messaging-host/win32-ia32
      - name: Download windows-arm64 artifact
        uses: actions/download-artifact@v2
        with:
          name: native-messaging-host-win32-arm64
          path: packages/native-messaging-host/win32-arm64
      - name: Set version
        run: sed -i "s/0.0.0/${GITHUB_REF/refs\/tags\//}/g" packages/native-messaging-host/package.json
      - name: Change file mode
        run: |
          chmod a+rx linux-x64/keeweb-native-messaging-host
          chmod a+rx darwin-arm64/keeweb-native-messaging-host
          chmod a+rx darwin-x64/keeweb-native-messaging-host
        working-directory: packages/native-messaging-host
      - name: Make the package
        run: |
          npm pack ./packages/native-messaging-host
          mv keeweb-keeweb-native-messaging-host-*.tgz keeweb-native-messaging-host.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: Extensions built from ${{ github.sha }}
          files: |
            keeweb-native-messaging-host.tgz
            extensions/*.zip
            xcode/dist/KeeWeb Connect.app.zip
            xcode/dist/KeeWeb Connect.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
