name: Publish Firefox Addon

on:
  pull_request: # TEMPORARY
  workflow_dispatch: # TEMPORARY
  push:
    tags:
      - '*'

jobs:
  publish-firefox-extension:
    runs-on: ubuntu-latest
    outputs:
      xpi_filepath: ${{ steps.sign.outputs.xpi_filepath }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install npm modules
        run: npm ci
      - name: Build
        run: npm run build-firefox
      - name: Sign
        id: sign
        env:
          WEB_EXT_API_KEY: ${{ vars.FIREFOX_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
        run: |
          npx web-ext sign --source-dir=./dist/firefox
          echo "xpi_filepath=$(ls web-ext-artifacts/*.xpi)" >> "$GITHUB_OUTPUT"
      - name: Publish
        env:
          WEB_EXT_API_KEY: ${{ vars.FIREFOX_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
        # https://mozilla.github.io/addons-server/topics/api/addons.html#upload-create
        run: |
            addon_version=$(jq -r '.version' manifest.json)
            file_path="web-ext-artifacts/keeweb_connect-$addon_version.zip"
            jwt=$(npm run --silent gen-ff-jwt)
            curl -X POST --header Authorization: JWT $jwt" \
                --form "channel=listed" \
                --form upload=@$file_path \
                https://addons.mozilla.org/api/v5/addons/upload/
